spring:
  application:
    name: user

  datasource:
    url: jdbc:mysql://localhost:3306/smartmarket?useSSL=false&serverTimezone=UTC
    username: root
    password: Chaara@06
    driver-class-name: com.mysql.cj.jdbc.Driver
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8082